### PR TITLE
Allow to choose minutes

### PR DESCRIPTION
**Pull request by Pako7**
Hi.

This is the code to choose minutes.

### CODE REVIEW

**Comment by Jivings** [comment]
Hey thanks for this! 

It looks as if you have editing the wrong file however. The `standalone.js` file is compiled from the `lib/js` directory. So the file you want to edit is `lib/js/datepicker.js` and then compile with `npm run build`. 

Sorry, the project definitely needs a proper contribution guide.

**Comment by Ganbin** [comment]
Thanks for the add of the minute picker. Great feature.
Could you integrate this pull request so we can use the minutes without having to install the @Pako7 repository?

**Comment by Ganbin** [comment]
Hi again, I have made the modification on the `lib/js/datepicker.js` and `lib/scss/picker.scss` But when I do `npm run build`, I get an error on the brwoserify command. That's the error I get :
```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:js"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! material-datetime-picker@1.0.1 build:js: `browserify -r rome -r moment > dist/vendor.js && browserify --no-bundle-external -s MaterialDatePicker -d ./datetime-picker.js > dist/js/datepicker.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-datetime-picker@1.0.1 build:js script 'browserify -r rome -r moment > dist/vendor.js && browserify --no-bundle-external -s MaterialDatePicker -d ./datetime-picker.js > dist/js/datepicker.js'.
```

So I'm unable to make a pull request because the `dist/js/datepicker.js` is then empty.

Could you help me to make it work? Thanks

**Comment by Ganbin** [comment]
Oups, I forget to link you to my repo and the changes I have made. Here it is (https://github.com/Ganbin/material-datetime-picker)

**Comment by Jivings** [comment]
@Ganbin Hey, sorry I don't really have any time to dedicate to this project, but if you paste the entire error then I can have a look?

**Comment by Ganbin** [comment]
Sorry for the delay. Here is the error : 

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle material-datetime-picker@1.0.1~prebuild: material-datetime-picker@1.0.1
6 silly lifecycle material-datetime-picker@1.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle material-datetime-picker@1.0.1~build: material-datetime-picker@1.0.1
8 verbose lifecycle material-datetime-picker@1.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle material-datetime-picker@1.0.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Gabriel/Desktop/material-datetime-picker/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin
10 verbose lifecycle material-datetime-picker@1.0.1~build: CWD: /Users/Gabriel/Desktop/material-datetime-picker
11 silly lifecycle material-datetime-picker@1.0.1~build: Args: [ '-c',
11 silly lifecycle   'mkdir -p dist/{js,css} && npm run build:css && npm run build:js' ]
12 silly lifecycle material-datetime-picker@1.0.1~build: Returned: code: 1  signal: null
13 info lifecycle material-datetime-picker@1.0.1~build: Failed to exec build script
14 verbose stack Error: material-datetime-picker@1.0.1 build: `mkdir -p dist/{js,css} && npm run build:css && npm run build:js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid material-datetime-picker@1.0.1
16 verbose cwd /Users/Gabriel/Desktop/material-datetime-picker
17 error Darwin 15.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error material-datetime-picker@1.0.1 build: `mkdir -p dist/{js,css} && npm run build:css && npm run build:js`
22 error Exit status 1
23 error Failed at the material-datetime-picker@1.0.1 build script 'mkdir -p dist/{js,css} && npm run build:css && npm run build:js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the material-datetime-picker package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     mkdir -p dist/{js,css} && npm run build:css && npm run build:js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs material-datetime-picker
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls material-datetime-picker
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
 
````

**Comment by nayak16** [comment]
Hey guys, friendly dev here wondering if this issue was ever fixed. Would love to use the datetime picker with minutes. Excellent job implementing this @Jivings

**Comment by jwhitfieldseed** [comment]
Hey, thanks for the PR. I'm the new maintainer for this project. It seems that the build system is holding back people from contributing (and using) the component right now, so I'm going to fix that first. Then I'll merge this feature.

@Ganbin - could you open a PR from your fork, please?

**Comment by jwhitfieldseed** [comment]
Closing in favour of #119, which follows the material design guidelines more closely.

**Pull request closed without merging**
