### PR TITLE
Add bower support

### LINKED ISSUE #84: Bower Support
Can you please add bower support?

### PR DESCRIPTION
**Pull request by Gorzas**
Close #84

### CODE REVIEW

**Comment by jwhitfieldseed** [comment]
Cool, thanks! I don't use Bower - what can I do to test this is working as expected?

**Comment by Gorzas** [comment]
I'm not sure that I've done it right but I think you should publish the package on bower like this: `bower register material-datetime-picker https://github.com/ripjar/material-datetime-picker`

**Comment by jwhitfieldseed** [comment]
OK, thanks. What about dependencies? Does bower need you to list them explicitly or does it co-operate with `package.json` for that?

If they must be explicit in `bower.json`, you'll need to add:

* moment @ 2.10.6
* rome @ https://github.com/jwhitfieldseed/rome.git#19f5d3031a922c29c52b9038b2832a827e5e99d6

If bower can't use that `rome` fork, `v2.1.22` _should_ work OK. I had to fix an issue with `rome` that prevented `rollup` from packaging it, but since you'll be using the already-compiled `material-datetime-picker.js`, bower users should not encounter that issue.

**Comment by Gorzas** [comment]
@jwhitfieldseed I'm not sure right now. I'm going to make a test with bower but I'm afraid that you're right and that without the dependencies inside the bower.json file it may not work correctly.

**Comment by Gorzas** [comment]
Added bower_components directory to .gitignore and the dependencies for bower. It's installing them now. Sorry.

**Comment by jwhitfieldseed** [comment]
Thanks for the update 😄 

I don't think that the `rome` version is right, though. 

That commit is from a fork of `rome`, and I don't see how bower would know how to use that fork instead of the repo in the bower registry. It looks like bower, upon failing to find that version, installs the default latest version.

It would be more explicit to depend on `2.1.22`.

Because the issue that the fork resolves happens at build time only, I think this is fine. The component works well with `moment` and `rome` from `bower_components`.

I'll merge once this change is made 👍

**Comment by Gorzas** [comment]
Changed to its version 2.1.22 :)

**Comment by jwhitfieldseed** [comment]
Thanks for the contribution 🎉

**Comment by jwhitfieldseed** [comment]
I registered the package:

```
❯ bower info material-datetime-picker
bower cached        https://github.com/ripjar/material-datetime-picker.git#1.0.1
bower validate      1.0.1 against https://github.com/ripjar/material-datetime-picker.git#*
bower new           version for https://github.com/ripjar/material-datetime-picker.git#*
bower resolve       https://github.com/ripjar/material-datetime-picker.git#*
bower download      https://github.com/ripjar/material-datetime-picker/archive/v2.0.0.tar.gz
bower extract       material-datetime-picker#* archive.tar.gz
bower resolved      https://github.com/ripjar/material-datetime-picker.git#2.0.0

{
  name: 'material-datetime-picker',
  homepage: 'https://github.com/ripjar/material-datetime-picker',
  version: '2.0.0'
}

Available versions:
  - 2.0.0
  - 1.0.1
  - 1.0.0
```

**Pull request merged**
